# Generated by Django 3.0.7 on 2020-08-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('age', models.IntegerField()),
                ('cname', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'Emp',
            },
        ),
    ]
