# Generated by Django 3.0.7 on 2020-08-14 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORMTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('stream', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORMTest.Emp')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
