# Generated by Django 3.0.7 on 2020-08-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORMTest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='address',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='cname',
        ),
        migrations.AddField(
            model_name='emp',
            name='comname',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='emp',
            name='empaddress',
            field=models.CharField(default='', max_length=200),
        ),
    ]
