# Generated by Django 3.0.7 on 2020-08-14 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORMTest', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('month', models.CharField(max_length=15)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORMTest.Emp')),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORMTest.Student')),
            ],
            options={
                'db_table': 'Account',
            },
        ),
    ]
