# Generated by Django 3.0.7 on 2020-08-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORMTest', '0002_auto_20200818_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='contact',
            field=models.IntegerField(max_length=12),
        ),
    ]
