# Generated by Django 3.0.7 on 2020-08-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('college', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('college', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
    ]
