# Generated by Django 3.0.3 on 2020-08-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emp',
            table='Emp',
        ),
    ]
