# Generated by Django 3.0.7 on 2020-10-06 07:03

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('address', models.TextField(max_length=300)),
            ],
            managers=[
                ('em', django.db.models.manager.Manager()),
            ],
        ),
    ]
